outputs: [report, exclusions]
#options are report, exclusions, and filtered

# Set to 'false' for automatic scanning of plink filesets,
#   provide single sample, or provide list
sample: false

# These are the files to be used for sex concordance QC. They must contain
#   X chromosomes. If left blank, standard plink filesets will be used. If
#   directory is provided, it will be scanned for plink files containing the
#   same names. If another string is provided, it will be used at the end of
#   the sample names.
SexIn: false

# This is the directory with the input files:
DataIn: .

# This is the directory with the output files:
DataOut: output

#Do the samples contain families (true/false):
family: false

superpop: EUR
king: true
pcair: true

QC:
  GenoMiss: 0.05
  SampMiss: 0.05
  MAF: 0.02
  HWE: 10e-30

download_tg: true
genome_build: hg19
