## snakejob -j 100 --keep-going --notemp --use-conda -np
# snakemake --use-conda --conda-create-envs-only --conda-frontend mamba -j1
# snakemake --forceall --rulegraph | dot -Tpdf > docs/dag2.pdf

outputs: [report, exclusions]
#options are report, exclusions, and filtered
nointernet: true
do_sexqc: false

# Set to 'false' for automatic scanning of plink filesets,
#   provide single sample, or provide list
sample: false

# These are the files to be used for sex concordance QC. They must contain
#   X chromosomes. If left blank, standard plink filesets will be used. If
#   directory is provided, it will be scanned for plink files containing the
#   same names. If another string is provided, it will be used at the end of
#   the sample names.
SexIn: original

# This is the directory with the input files:
DataIn: postImpute

# This is the directory with the output files:
DataOut: output

#Do the samples contain families (true/false):
family: false

superpop: EUR
king: true
pcair: true

QC:
  GenoMiss: 0.05
  SampMiss: 0.05
  MAF: 0.01
  HWE: 10e-30

download_tg: true
genome_build: hg19
mirror: ebi # ncbi or ebi

union_panel: true #make sure population ref panel and sample snps all overlap
union_extra: true #require snp overlap with extra ref if present

# custom_ref_name: The name of a custom reference set, if using a custom main reference.
#   This should be descriptive and not contain whitespace, underscores or periods
#   DO NOT call it 1kG or extraref, as those are reserved names.
custom_ref_name: false
#fooby
# custom_ref: the file, filestem or fileset with your custom reference, if using a custom ref.
#   It can be the filestem for a binary PLINK fileset containing all chromosomes.
#   for VCF references, give the filename. If there is a file for each chromosomem,
#     {chrom} will be replaced with the chromosome number
custom_ref: false
  #inputs/foo.bar_baz # inputs/foo.baz_bar.vcf.gz #inputs/foo.bar_baz_chr{chrom}.qux.vcf.gz
# custom_pops: file with the header "FID IID Population"
#   and FID, IID and subpopulation in each row.
#   file should be space-separated and have entries for all ref samples
#   if you are using a VCF reference, FID should be the VCF sample ID befpre the first underscore,
#     and IID shhould be everything after. If there are no underscores, FID and IID should both
#     be the VCF sample ID.
custom_pops: false


# extra_ref: the file, filestem or fileset with your extra reference, if using an extra ref.
#   It can be the filestem for a binary PLINK fileset containing all chromosomes.
#   for VCF references, give the filename. If there is a file for each chromosomem,
#     {chrom} will be replaced with the chromosome number
extra_ref: false
# subpopulation code for your additional reference. It should be a subpopulation of the superpop or not be a 1kgp population
extra_ref_subpop: false
