# This config file should only be used directly with ancestry.smk
#  It will NOT override the options in the main "config.yaml"

ref_only: true # optional here but required if directly using as module
genome_build: ['hg19', 'hg38']
GenoMiss: [0.05]

# The below options are OPTIONAL and can be removed from this file
custom_ref:
# name: The name of a custom reference set, if using a custom main reference.
#   This should be descriptive and not contain whitespace, underscores or periods
#   DO NOT call it 1kG or extraref, as those are reserved names.
  name: false
# file: the file, filestem or fileset with your custom reference, if using a custom ref.
#   It can be the filestem for a binary PLINK fileset containing all chromosomes.
#   for VCF references, give the filename. If there is a file for each chromosomem,
#     {chrom} will be replaced with the chromosome number
  file: false
  #inputs/foo.bar_baz # inputs/foo.baz_bar.vcf.gz #inputs/foo.bar_baz_chr{chrom}.qux.vcf.gz
# custom_pops: file with the header "FID IID Population"
#   and FID, IID and subpopulation in each row.
#   file should be space-separated and have entries for all ref samples
#   if you are using a VCF reference, FID should be the VCF sample ID befpre the first underscore,
#     and IID shhould be everything after. If there are no underscores, FID and IID should both
#     be the VCF sample ID.
  custom_pops: false
